name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      flags:
        description: 'Feature flag names (comma separated)'
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
  unit:
    runs-on: ubuntu-latest
    needs: [lint, unit]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: npm ci

      - name: Unit Tests
        run: npm run test:unit
  e2e:
    needs: [lint, unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: npm ci

      - name: Test - Chrome
        run: npm run wdio -- --target=chrome ${{ github.event.inputs.flags && format('--flags={0}', github.event.inputs.flags) || '' }}

      - name: Test - Firefox
        run: npm run wdio -- --target=firefox ${{ github.event.inputs.flags && format('--flags={0}', github.event.inputs.flags) || '' }}
  e2e-update:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: npm ci

      - name: Test - Chrome
        run: npm run wdio:update -- --target=chrome ${{ github.event.inputs.flags && format('--flags={0}', github.event.inputs.flags) || '' }}

      - name: Test - Firefox
        run: npm run wdio:update -- --target=firefox ${{ github.event.inputs.flags && format('--flags={0}', github.event.inputs.flags) || '' }}
  e2e-no-flags:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.tool-versions'

      - name: Install dependencies
        run: npm ci

      - name: Test - Chrome
        run: npm run wdio -- --target=chrome --flags=

      - name: Test - Firefox
        run: npm run wdio -- --target=firefox --flags=
